### ISSUE TITLE
Inaccurate version bounds in  .cabal file (mono-traversable)

### ISSUE THREAD

**Issue by hvr** [fpco/mutable-containers#6]
Here's one falsifying example:

```
Preprocessing library mutable-containers-0.3.2.1...
[1 of 8] Compiling Data.Mutable.Class ( Data/Mutable/Class.hs, /tmp/mutable-containers-0.3.2.1/dist-newstyle/build/mutable-containers-0.3.2.1/build/Data/Mutable/Class.o ) [Data.Sequences changed]

Data/Mutable/Class.hs:296:10-20:
    Not in scope: ‘Seqs.unsnoc’
    Perhaps you meant ‘Seqs.uncons’ (imported from Data.Sequences)

Data/Mutable/Class.hs:333:33-43: Not in scope: ‘Seqs.snoc’
```

needs e.g. `mono-traversable >= 0.3` (maybe even `>= 0.2` works -- but couldn't easily verify that)

**Comment by juhp** [comment]
This prevents me from building stack-1.1.2 btw.

**Comment by mgsloan** [comment]
@juhp Fixed in https://github.com/commercialhaskell/stack/commit/93cedb7ce20d1fcc4f46d4b0b38b7842d44bad20 in theory (thanks for the heads up @hvr!)

**Comment by hvr** [comment]
@mgsloan not sure how that commit relates to this; anyway I'm going to edit in a few lower bounds to the affected mutable-containers releases... that should fix `stack-1.1.2`

**Comment by mgsloan** [comment]
Oh, I read too quickly, sorry for the noise!

**Comment by hvr** [comment]
@juhp should work now

**Comment by juhp** [comment]
Awesome thanks!

**Comment by snoyberg** [comment]
Closing, as this repo is now deprecated
